name: to_ecr
on:
  push:
    tags:
      - v*
env:
 CI_COMMIT_REF_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - uses: actions/checkout@v4
      - name: Run a script
        run: echo $CI_COMMIT_REF_NAME